#!/usr/bin/env bash
# configures new ubuntu machine with certain nginx requirements
sudo apt-get update -y
sudo apt-get install nginx -y
echo 'Hello World!' > /var/www/html/index.html
service nginx restart
