#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

apt-get -y update
apt-get -y install haproxy=1.6.\*

echo '
frontend markjkelvin.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 232528-web-01 34.203.33.205
        server 232528-web-02 54.210.127.27
' >> /etc/haproxy/haproxy.cfg

service haproxy restart
