#!/usr/bin/env bash
# This script is displaying "Best School"
m=0

while ((m < 10))
do
	((m++))
	if [ $m -eq 4 ]
	then
		echo "bad luck"
	elif [ $m -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
