#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

m=1

while ((m <21))
do
	echo $m
	case "$m" in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
		esac
	((m++))
done
